language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "pypy"
matrix:
    allow_failures:
        - python: "pypy"
install:
    - pip install -r devel-requirements.txt --use-mirrors
    - pip install -e .
script:
    - python -c 'import deps; print(deps.__version__)'
    - nosetests
    - pep8 vip

